### ISSUE TITLE
ERR_INVALID_ARG_TYPE, program won't run

### ISSUE THREAD

**Issue by zachjord** [DoctorMcKay/Steam-Card-Farmer#39]
I receive the following error when trying to run steamcardfarmer. I think it's been like this for a few months now, I just haven't had a need to run the program in a while.

```
prompt: username:  (node:11971) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
prompt: username:  
prompt: password:  
2020-08-12 18:43:55 - Initializing Steam client...
Steam Guard App Code: 
internal/fs/utils.js:701
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (65)
    at Object.writeFile (fs.js:1385:5)
    at FileStorage.saveFile.FileStorage.writeFile (/usr/lib/node_modules/steam-card-farmer/node_modules/file-manager/index.js:68:5)
    at SteamUser._handlers.<computed> (/usr/lib/node_modules/steam-card-farmer/node_modules/steam-user/components/logon.js:294:18)
    at SteamUser._handleMessage (/usr/lib/node_modules/steam-card-farmer/node_modules/steam-user/components/messages.js:249:30)
    at CMClient.emit (events.js:314:20)
    at CMClient._netMsgReceived (/usr/lib/node_modules/steam-card-farmer/node_modules/steam-user/node_modules/steam-client/lib/cm_client.js:323:8)
    at CMClient.handlers.<computed> (/usr/lib/node_modules/steam-card-farmer/node_modules/steam-user/node_modules/steam-client/lib/cm_client.js:609:8)
    at CMClient._netMsgReceived (/usr/lib/node_modules/steam-card-farmer/node_modules/steam-user/node_modules/steam-client/lib/cm_client.js:305:24)
    at TCPConnection.emit (events.js:314:20)
    at TCPConnection._readPacket (/usr/lib/node_modules/steam-card-farmer/node_modules/steam-user/node_modules/steam-client/lib/tcp_connection.js:183:7) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by DoctorMcKay** [comment]
Have you tried `npm update`? If that doesn't work, try deleting node_modules and running `npm install` again.

**Comment by mmarkus13** [comment]
I'm having the same issue.

```
2023-03-08 10:02:12 - Reading Steam credentials from command line
(node:20500) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Steam Guard App Code: XXXXXX
node:internal/fs/utils:901
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (93)
    at Object.writeFile (node:fs:2196:5)
    at FileStorage.saveFile.FileStorage.writeFile (C:\Users\RTX 3060 12Gb\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\file-manager\index.js:68:5)
    at SteamUser._handlers.<computed> (C:\Users\RTX 3060 12Gb\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam-user\components\logon.js:294:18)
    at SteamUser._handleMessage (C:\Users\RTX 3060 12Gb\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam-user\components\messages.js:249:30)
    at CMClient.emit (node:events:513:28)
    at CMClient._netMsgReceived (C:\Users\RTX 3060 12Gb\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam-user\node_modules\steam-client\lib\cm_client.js:323:8)
    at handlers.<computed> (C:\Users\RTX 3060 12Gb\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam-user\node_modules\steam-client\lib\cm_client.js:609:8)
    at CMClient._netMsgReceived (C:\Users\RTX 3060 12Gb\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam-user\node_modules\steam-client\lib\cm_client.js:305:24)
    at TCPConnection.emit (node:events:513:28)
    at TCPConnection._readPacket (C:\Users\RTX 3060 12Gb\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam-user\node_modules\steam-client\lib\tcp_connection.js:183:7) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.15.0

**Comment by mmarkus13** [comment]
I'm having the same issue:

```2023-03-08 10:02:12 - Reading Steam credentials from command line
(node:20500) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Steam Guard App Code: XXXXXX
node:internal/fs/utils:901
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (93)
    at Object.writeFile (node:fs:2196:5)
    at FileStorage.saveFile.FileStorage.writeFile (C:\Users\RTX 3060 12Gb\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\file-manager\index.js:68:5)
    at SteamUser._handlers.<computed> (C:\Users\RTX 3060 12Gb\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam-user\components\logon.js:294:18)
    at SteamUser._handleMessage (C:\Users\RTX 3060 12Gb\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam-user\components\messages.js:249:30)
    at CMClient.emit (node:events:513:28)
    at CMClient._netMsgReceived (C:\Users\RTX 3060 12Gb\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam-user\node_modules\steam-client\lib\cm_client.js:323:8)
    at handlers.<computed> (C:\Users\RTX 3060 12Gb\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam-user\node_modules\steam-client\lib\cm_client.js:609:8)
    at CMClient._netMsgReceived (C:\Users\RTX 3060 12Gb\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam-user\node_modules\steam-client\lib\cm_client.js:305:24)
    at TCPConnection.emit (node:events:513:28)
    at TCPConnection._readPacket (C:\Users\RTX 3060 12Gb\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam-user\node_modules\steam-client\lib\tcp_connection.js:183:7) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.15.0```

**Comment by mmarkus13** [comment]
When running from under Windows10 WSL2 (Ubuntu 22.04.02 LTS) it looks better, but also results in error:

```2023-03-08 10:15:47 - Logged into Steam!
2023-03-08 10:15:47 - Waiting for license info...
/usr/local/lib/node_modules/steam-card-farmer/node_modules/binarykvparser/index.js:23
        if (buffer.toBuffer) {
                   ^

TypeError: Cannot read property 'toBuffer' of null
    at Object.exports.parse (/usr/local/lib/node_modules/steam-card-farmer/node_modules/binarykvparser/index.js:23:13)
    at /usr/local/lib/node_modules/steam-card-farmer/node_modules/steam-user/components/apps.js:177:36
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/steam-card-farmer/node_modules/steam-user/components/apps.js:173:26
    at Object.cb (/usr/local/lib/node_modules/steam-card-farmer/node_modules/steam-user/components/messages.js:174:4)
    at CMClient._netMsgReceived (/usr/local/lib/node_modules/steam-card-farmer/node_modules/steam-user/node_modules/steam-client/lib/cm_client.js:321:26)
    at CMClient.handlers.<computed> (/usr/local/lib/node_modules/steam-card-farmer/node_modules/steam-user/node_modules/steam-client/lib/cm_client.js:609:8)
    at CMClient._netMsgReceived (/usr/local/lib/node_modules/steam-card-farmer/node_modules/steam-user/node_modules/steam-client/lib/cm_client.js:305:24)
    at TCPConnection.emit (events.js:314:20)
    at TCPConnection._readPacket (/usr/local/lib/node_modules/steam-card-farmer/node_modules/steam-user/node_modules/steam-client/lib/tcp_connection.js:183:7)
root@DESKTOP-TDJF6C5:/mnt/c/Users/RTX 3060 12Gb/Downloads/Steam-Card-Farmer-old-cli/Steam-Card-Farmer-old-cli#

**Comment by roughnecks** [comment]
```
2023-07-09 01:03:20 - Reading Steam credentials from command line
(node:41) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Steam Guard App Code: 6n6rp
node:internal/fs/utils:890
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (184)
    at Object.writeFile (node:fs:2168:5)
    at FileStorage.saveFile.FileStorage.writeFile (/usr/local/lib/node_modules/steam-card-farmer/node_modules/file-manager/index.js:68:5)
    at SteamUser._handlers.<computed> (/usr/local/lib/node_modules/steam-card-farmer/node_modules/steam-user/components/logon.js:294:18)
    at SteamUser._handleMessage (/usr/local/lib/node_modules/steam-card-farmer/node_modules/steam-user/components/messages.js:249:30)
    at CMClient.emit (node:events:513:28)
    at CMClient._netMsgReceived (/usr/local/lib/node_modules/steam-card-farmer/node_modules/steam-user/node_modules/steam-client/lib/cm_client.js:323:8)
    at handlers.<computed> (/usr/local/lib/node_modules/steam-card-farmer/node_modules/steam-user/node_modules/steam-client/lib/cm_client.js:609:8)
    at CMClient._netMsgReceived (/usr/local/lib/node_modules/steam-card-farmer/node_modules/steam-user/node_modules/steam-client/lib/cm_client.js:305:24)
    at TCPConnection.emit (node:events:513:28)
    at TCPConnection._readPacket (/usr/local/lib/node_modules/steam-card-farmer/node_modules/steam-user/node_modules/steam-client/lib/tcp_connection.js:183:7) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.13.0
```

I'm on Debian Bookworm WSL2
