### ISSUE TITLE
error

### ISSUE THREAD

**Issue by napinacz2** [DoctorMcKay/Steam-Card-Farmer#8]
getting this error in version 1.5.0,

Microsoft Windows XP [Wersja 5.1.2600]
(C) Copyright 1985-2001 Microsoft Corp.

2015-06-27 06:11:38 - Reading Steam credentials from command line
2015-06-27 06:11:39 - Logged into Steam!
2015-06-27 06:11:39 - Waiting for license info...
2015-06-27 06:11:39 - Got 49 owned licenses. Requesting package info...
C:\Documents and Settings\--\Dane aplikacji\npm\node_modules\steam-card-farmer\n
ode_modules\steam\node_modules\binarykvparser\node_modules\bytebuffer\dist\ByteB
ufferNB.js:353
                throw TypeError("Illegal buffer");
                      ^
TypeError: Illegal buffer
    at TypeError (native)
    at Function.module.exports.ByteBuffer.wrap (C:\Documents and Settings\--\Dan
e aplikacji\npm\node_modules\steam-card-farmer\node_modules\steam\node_modules\b
inarykvparser\node_modules\bytebuffer\dist\ByteBufferNB.js:353:23)
    at Object.exports.parse (C:\Documents and Settings\--\Dane aplikacji\npm\nod
e_modules\steam-card-farmer\node_modules\steam\node_modules\binarykvparser\index
.js:17:23)
    at C:\Documents and Settings\--\Dane aplikacji\npm\node_modules\steam-card-f
armer\node_modules\steam\lib\handlers\steamapps.js:75:44
    at Array.forEach (native)
    at SteamClient.handlers.(anonymous function) (C:\Documents and Settings\--\D
ane aplikacji\npm\node_modules\steam-card-farmer\node_modules\steam\lib\handlers
\steamapps.js:72:26)
    at SteamClient._netMsgReceived (C:\Documents and Settings\--\Dane aplikacji\
npm\node_modules\steam-card-farmer\node_modules\steam\lib\steam_client.js:107:26
)
    at SteamClient.handlers.(anonymous function) (C:\Documents and Settings\--\D
ane aplikacji\npm\node_modules\steam-card-farmer\node_modules\steam\lib\steam_cl
ient.js:193:10)
    at SteamClient._netMsgReceived (C:\Documents and Settings\--\Dane aplikacji\
npm\node_modules\steam-card-farmer\node_modules\steam\lib\steam_client.js:107:26
)
    at Connection.emit (events.js:107:17)

**Comment by chepeme** [comment]
Same happends to me.

On Archlinux 

[pi@raspberrypi ~]$ steamcardfarmer
prompt: username:  "lolailoxDD"
prompt: password:
2015-06-25 21:37:52 - Initializing Steam client...
2015-06-25 21:37:55 - Logged into Steam!
2015-06-25 21:37:55 - Waiting for license info...
2015-06-25 21:37:55 - Got 251 owned licenses. Requesting package info...
/usr/lib/node_modules/steam-card-farmer/node_modules/steam/node_modules/binarykvparser/node_modules/bytebuffer/dist/ByteBufferNB.js:353
                throw TypeError("Illegal buffer");
                      ^
TypeError: Illegal buffer
    at TypeError (native)
    at Function.module.exports.ByteBuffer.wrap (/usr/lib/node_modules/steam-card-farmer/node_modules/steam/node_modules/binarykvparser/node_modules/bytebuffer/dist/ByteBufferNB.js:353:23)
    at Object.exports.parse (/usr/lib/node_modules/steam-card-farmer/node_modules/steam/node_modules/binarykvparser/index.js:17:23)
    at /usr/lib/node_modules/steam-card-farmer/node_modules/steam/lib/handlers/steamapps.js:75:44
    at Array.forEach (native)
    at SteamClient.handlers.(anonymous function) (/usr/lib/node_modules/steam-card-farmer/node_modules/steam/lib/handlers/steamapps.js:72:26)
    at SteamClient._netMsgReceived (/usr/lib/node_modules/steam-card-farmer/node_modules/steam/lib/steam_client.js:107:26)
    at SteamClient.handlers.(anonymous function) (/usr/lib/node_modules/steam-card-farmer/node_modules/steam/lib/steam_client.js:193:10)
    at SteamClient._netMsgReceived (/usr/lib/node_modules/steam-card-farmer/node_modules/steam/lib/steam_client.js:107:26)
    at Connection.emit (events.js:107:17)
[pi@raspberrypi ~]$


On Windows

C:\Users\LAS FLORITAS>steamcardfarmer
prompt: username:  "lolailoxDD"
prompt: password:
2015-06-25 22:22:39 - Initializing Steam client...
Steam Guard Email Code: 
2015-06-25 22:22:57 - Logged into Steam!
2015-06-25 22:22:57 - Waiting for license info...
2015-06-25 22:22:57 - Got 251 owned licenses. Requesting package info...
C:\Users\LAS FLORITAS\AppData\Roaming\npm\node_modules\steam-card-farmer\node_mo
dules\steam\node_modules\binarykvparser\node_modules\bytebuffer\dist\ByteBufferN
B.js:353
                throw TypeError("Illegal buffer");
                      ^
TypeError: Illegal buffer
    at TypeError (native)
    at Function.module.exports.ByteBuffer.wrap (C:\Users\LAS FLORITAS\AppData\Ro
aming\npm\node_modules\steam-card-farmer\node_modules\steam\node_modules\binaryk
vparser\node_modules\bytebuffer\dist\ByteBufferNB.js:353:23)
    at Object.exports.parse (C:\Users\LAS FLORITAS\AppData\Roaming\npm\node_modu
les\steam-card-farmer\node_modules\steam\node_modules\binarykvparser\index.js:17
:23)
    at C:\Users\LAS FLORITAS\AppData\Roaming\npm\node_modules\steam-card-farmer\
node_modules\steam\lib\handlers\steamapps.js:75:44
    at Array.forEach (native)
    at SteamClient.handlers.(anonymous function) (C:\Users\LAS FLORITAS\AppData\
Roaming\npm\node_modules\steam-card-farmer\node_modules\steam\lib\handlers\steam
apps.js:72:26)
    at SteamClient._netMsgReceived (C:\Users\LAS FLORITAS\AppData\Roaming\npm\no
de_modules\steam-card-farmer\node_modules\steam\lib\steam_client.js:107:26)
    at SteamClient.handlers.(anonymous function) (C:\Users\LAS FLORITAS\AppData\
Roaming\npm\node_modules\steam-card-farmer\node_modules\steam\lib\steam_client.j
s:193:10)
    at SteamClient._netMsgReceived (C:\Users\LAS FLORITAS\AppData\Roaming\npm\no
de_modules\steam-card-farmer\node_modules\steam\lib\steam_client.js:107:26)
    at Connection.emit (events.js:107:17)

C:\Users\LAS FLORITAS>

**Comment by Avaray** [comment]
Are you using Node.js v 0.12+ ?

**Comment by chepeme** [comment]
Yes.
 On windows: Your environment has been set up for using Node.js 0.12.5 (ia32) and npm.
On Archlinux :
[pi@raspberrypi ~]$ node -v
v0.12.5

**Comment by Avaray** [comment]
Damn. I have same issue at my second OS: Ubuntu 15.04.

**Comment by carlesreig** [comment]
Same problem here, win 7 64bits (spanish language), tested with latest nodejs and iojs 64bits instalation.

C:\Windows\system32>steamcardfarmer
prompt: username:  steamuser
prompt: password:
2015-07-01 10:46:50 - Initializing Steam client...
2015-07-01 10:46:51 - Logged into Steam!
2015-07-01 10:46:51 - Waiting for license info...
2015-07-01 10:46:51 - Got 473 owned licenses. Requesting package info...
C:\Users\hande\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam\node_modules\binarykvparser\node_modules\bytebuffer\dist\ByteBufferNB.js:353
                throw TypeError("Illegal buffer");
                      ^
TypeError: Illegal buffer
    at TypeError (native)
    at Function.module.exports.ByteBuffer.wrap (C:\Users\hande\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam\node_modules\binarykvparser\node_modules\bytebuffer\dist\ByteBufferNB.js:353:23)
    at Object.exports.parse (C:\Users\hande\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam\node_modules\binarykvparser\index.js:17:23)
    at C:\Users\hande\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam\lib\handlers\steamapps.js:75:44
    at Array.forEach (native)
    at SteamClient.handlers.(anonymous function) (C:\Users\hande\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam\lib\handlers\steamapps.js:72:26)
    at SteamClient._netMsgReceived (C:\Users\hande\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam\lib\steam_client.js:107:26)
    at SteamClient.handlers.(anonymous function) (C:\Users\hande\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam\lib\steam_client.js:193:10)
    at SteamClient._netMsgReceived (C:\Users\hande\AppData\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam\lib\steam_client.js:107:26)
    at emitOne (events.js:77:13)

**Comment by Kasetto** [comment]
And same problem here: win7 64 bit (pl language)

Microsoft Windows [Wersja 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Wszelkie prawa zastrzeżone.

C:\Users\Administrator\AppData\Roaming\npm>steamcardfarmer.cmd
prompt: username:  blablabla
prompt: password:
2015-07-07 00:14:15 - Initializing Steam client...
2015-07-07 00:14:16 - Logged into Steam!
2015-07-07 00:14:16 - Waiting for license info...
2015-07-07 00:14:16 - Got 39 owned licenses. Requesting package info...
C:\Users\Administrator\AppData\Roaming\npm\node_modules\steam-card-farmer\node_m
odules\steam\node_modules\binarykvparser\node_modules\bytebuffer\dist\ByteBuffer
NB.js:353
                throw TypeError("Illegal buffer");
                      ^
TypeError: Illegal buffer
    at TypeError (native)
    at Function.module.exports.ByteBuffer.wrap (C:\Users\Administrator\AppData\R
oaming\npm\node_modules\steam-card-farmer\node_modules\steam\node_modules\binary
kvparser\node_modules\bytebuffer\dist\ByteBufferNB.js:353:23)
    at Object.exports.parse (C:\Users\Administrator\AppData\Roaming\npm\node_mod
ules\steam-card-farmer\node_modules\steam\node_modules\binarykvparser\index.js:1
7:23)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\steam-card-farmer
\node_modules\steam\lib\handlers\steamapps.js:75:44
    at Array.forEach (native)
    at SteamClient.handlers.(anonymous function) (C:\Users\Administrator\AppData
\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam\lib\handlers\stea
mapps.js:72:26)
    at SteamClient._netMsgReceived (C:\Users\Administrator\AppData\Roaming\npm\n
ode_modules\steam-card-farmer\node_modules\steam\lib\steam_client.js:107:26)
    at SteamClient.handlers.(anonymous function) (C:\Users\Administrator\AppData
\Roaming\npm\node_modules\steam-card-farmer\node_modules\steam\lib\steam_client.
js:193:10)
    at SteamClient._netMsgReceived (C:\Users\Administrator\AppData\Roaming\npm\n
ode_modules\steam-card-farmer\node_modules\steam\lib\steam_client.js:107:26)
    at Connection.emit (events.js:107:17)

THX.

**Comment by carlesreig** [comment]
To solve this error i just uninstalled nodejs (maybe it's not a must), then removed "npm" folder and all it's content (located here C:\Users\user_name\AppData\Roaming\npm and C:\Users\user_name\AppData\Roaming\npm_cache), and installed again.

**Comment by DoctorMcKay** [comment]
Everyone who's experiencing this error, please try removing the app `npm remove -g steam-card-farmer` then re-install it `npm install -g steam-card-farmer`.

It seems like there are some bad versions of stuff that npm is installing for some reason.

**Comment by Avaray** [comment]
Fix from DoctorMcKay works for me. Thanks :)
