### ISSUE TITLE
Error On Fedora 22

### ISSUE THREAD

**Issue by AKnightWhoSaysNi** [DoctorMcKay/Steam-Card-Farmer#9]
2015-07-03 21:00:10 - Initializing Steam client...

/usr/lib/node_modules/steam-card-farmer/node_modules/steam/lib/steam_client.js:151
  var cryptedSessKey = require('crypto').publicEncrypt(fs.readFileSync(__dirna
                                         ^
TypeError: Object #<Object> has no method 'publicEncrypt'
    at SteamClient.handlers.(anonymous function) (/usr/lib/node_modules/steam-card-farmer/node_modules/steam/lib/steam_client.js:151:42)
    at SteamClient._netMsgReceived (/usr/lib/node_modules/steam-card-farmer/node_modules/steam/lib/steam_client.js:107:26)
    at Connection.emit (events.js:95:17)
    at Connection._readPacket (/usr/lib/node_modules/steam-card-farmer/node_modules/steam/lib/connection.js:50:8)
    at Connection.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Connection.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)

Doesn't matter what I put in for the credentials

**Comment by AKnightWhoSaysNi** [comment]
Okay the problem was that I forgot to run node.js (lol) but now I'm getting this error once it finds the amount of trading cards:

2015-07-03 21:31:32 - Initializing Steam client...
2015-07-03 21:31:32 - Logged into Steam!
2015-07-03 21:31:32 - Waiting for license info...
2015-07-03 21:31:32 - Got 28 owned licenses. Requesting package info...
/usr/lib/node_modules/steam-card-farmer/node_modules/steam/node_modules/binarykvparser/node_modules/bytebuffer/dist/ByteBufferNB.js:353
                throw TypeError("Illegal buffer");
                      ^
TypeError: Illegal buffer
    at TypeError (native)
    at Function.module.exports.ByteBuffer.wrap (/usr/lib/node_modules/steam-card-farmer/node_modules/steam/node_modules/binarykvparser/node_modules/bytebuffer/dist/ByteBufferNB.js:353:23)
    at Object.exports.parse (/usr/lib/node_modules/steam-card-farmer/node_modules/steam/node_modules/binarykvparser/index.js:17:23)
    at /usr/lib/node_modules/steam-card-farmer/node_modules/steam/lib/handlers/steamapps.js:75:44
    at Array.forEach (native)
    at SteamClient.handlers.(anonymous function) (/usr/lib/node_modules/steam-card-farmer/node_modules/steam/lib/handlers/steamapps.js:72:26)
    at SteamClient._netMsgReceived (/usr/lib/node_modules/steam-card-farmer/node_modules/steam/lib/steam_client.js:107:26)
    at SteamClient.handlers.(anonymous function) (/usr/lib/node_modules/steam-card-farmer/node_modules/steam/lib/steam_client.js:193:10)
    at SteamClient._netMsgReceived (/usr/lib/node_modules/steam-card-farmer/node_modules/steam/lib/steam_client.js:107:26)
    at Connection.emit (events.js:107:17)

**Comment by Avaray** [comment]
2 open issues is too much to read, right?
https://github.com/DoctorMcKay/Steam-Card-Farmer/issues/8
